### ISSUE TITLE
size of text substantially increases sentiment range

### ISSUE THREAD

**Issue by cromulus** [7compass/sentimental#18]
I've noticed that the size of the text evaluated substantially increases the range of the sentiment scores.

Single sentences will result in a score between -1 and 1, however, multi-line paragraphs can create scores in excess of 10 and -10.

For example, the Gettysburg address produces a score of -4.7, and the latest blog post from positivityblog gets a score of 4.8.

I can't share the texts that I'm seeing scores of 11 and 12 from, unfortunately.

Is this expected behavior? If so, how should I go about normalizing the score so I can compare it to other scores in between -1 and 1?

**Comment by denispasin** [comment]
The way the algorithm work is summing the scores of positive words (not exactly depending on which option you use but that's the idea). So yes, a longer text will have a bigger score.

Do you really require to compare the positiveness of two text ? If yes, i would divide each text score by something based on the number of words/sentences in the text.

**Comment by cromulus** [comment]
got it. thanks!

**Comment by denispasin** [comment]
You're welcome :)
