### ISSUE TITLE
Change to the scoring system!

### ISSUE THREAD

**Issue by praserocking** [7compass/sentimental#5]
why dont we take an average of all the scores of the tokens in the sentence as score? its currently calculated as the sum only! if we take average , it will fall between -1 to 1 right?

**Comment by agarie** [comment]
Yes, it will fall inside [-1, 1]. However, by summing the weights of each word, a sentence being longer (or shorter) will also influence how strong the sentiment can be.

There are several ways to utilize this information (a variable threshold, morphosyntactic analysis to increase the importance of nouns and adjectives, etc) but one of the key points of this gem is its simplicity, IMO. Not that your proposed change is complicated, but still. :P

Do you have a specific user case that would justify this change?

**Comment by praserocking** [comment]
I am currently using this gem to analyse sentiment of few reviews given to flipkart.com on their FB page, I get a lot of negative posts marked as positive, where he used a negative words along with a few positive word to express his views.. those posts got marked as positive! 
"""
Very much amazed to come across that "in a day guaranteed delivery doesn't work.. my order id is OD202226028103118000 it was given that today is the delivery day, but now its showing delivery will be 7th of march. it was a birthday gift now is going to compensate on this.
"""
this negative review gets  a score of 1.03125

**Comment by agarie** [comment]
I see. This is a bit harder. You can probably define a better threshold if the scores are bounded to [-1, 1] as you said, but maybe you should try building a problem-specific dictionary, i.e. given your list of reviews, adjusting the weight of each word in the dictionary to more closely resemble what you see?

Another option is to calculate the score for each of your current reviews and see if there is a clear threshold for negative reviews. For example, you might find that your specific set of texts should use a threshold of 2.5 (I'm guessing) to correctly separate negative and positive reviews.

**Comment by praserocking** [comment]
oh that makes sense , thanks @agarie , I'll try to run this over a set of negative reviews and try to find a more suitable threshold to use! :+1: and I've already customised the slang dictionary a little to match to my test cases..
